import { sequence } from '@withl5e/l5e/middleware';
import { fromFetchMiddleware } from '@withl5e/l5e/i18n';
// Generated by `paraglide-js compile` (see package.json's `i18n:compile` script).
import { paraglideMiddleware } from '~/paraglide/server.js';

export const onRequest = sequence(fromFetchMiddleware(paraglideMiddleware));
